### PR TITLE
New version of mod_sound with PSVita fixes

### PR DESCRIPTION
**Pull request by danielt3**
This version of mod_sound was created by the original BennuGD author and fixes a number of issues in the PSVita version.

Please, review and merge it.

### CODE REVIEW

**Comment by isage** [comment]
Either you messed something up, or it changes nothing

**Comment by danielt3** [comment]
I think it does changes some stuff.

image

**Comment by isage** [comment]
That does nothing functionally, except slightly reorganizing code

**Comment by danielt3** [comment]
It is not just reorganizing code: if `SDL_RWFromBGDFP` fails but `Mix_LoadWAV_RW` doesn't, file_close won't be called and `fp` will leak. In other words, we have to test the return of `SDL_RWFromBGDFP` before moving on with the execution and handle this failure (if some) before doing other things.

**Comment by isage** [comment]
Mix_LoadWAV_RW will fail if SDL_RWFromBGDFP fails (because when it fails it returns NULL).
See https://github.com/libsdl-org/SDL_mixer/blob/release-2.0.4/mixer.c#L681

**Comment by SplinterGU** [comment]
> Mix_LoadWAV_RW will fail if SDL_RWFromBGDFP fails (because when it fails it returns NULL). See https://github.com/libsdl-org/SDL_mixer/blob/release-2.0.4/mixer.c#L681

If the Mix_LoadWAV_RW fail for null rw_ops argument then ir don't release the file handle (file_close), if it fail later (in the load) then it do a file_close... Then Is wong that hoy in mod_sound.c do a file_close allways that it fail... The patch Is needed.. if you do file_close if it fail, you'll generarte double file_close AND a crash... Please apply the fix... Thsnks

**Comment by SplinterGU** [comment]
> That does nothing functionally, except slightly reorganizing code

Isn't only reorganizing code... It's needed, because sdl_mixer don't manage the errors good...

**Pull request merged**
